### ISSUE TITLE
Issue 04 - add 2044 a world governed by DAOs to News

### ISSUE THREAD

**Issue by yermoo** [aragon/aragon-monthly#102]
# Request for content

News

### Description of the requested content
we collaborate to promote the DAO http://yermoo.net/2044-a-world-governed-by-daos/

### Aditional information
Tag: DAOs

#### Deadline
By the end of the month, in time for Aragon Monthly issue 04

- [x] I would like to have a bounty on this Issue that I will fund myself

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xa0fa8a8aec7ecab96b6a2a721f84ee29ecbfcfcaa6227e9fef9af4296f88975b](https://etherscan.io/tx/0xa0fa8a8aec7ecab96b6a2a721f84ee29ecbfcfcaa6227e9fef9af4296f88975b)

**Comment by yermoo** [comment]
hello @john-light, thanks for adding
do I have to do something besides start the issue?
I'm little experienced with Github yet

**Comment by Smokyish** [comment]
Closed in #138
