### ISSUE TITLE
Issue 05 - add Never Heard of a DAO? Here's Why It's Going to Become The Hottest New Type of Corporation. to News

### ISSUE THREAD

**Issue by yutarond** [aragon/aragon-monthly#110]
### Request type:
 _News_ 

### Description of the requested content
[https://www.inc.com/darren-heitner/never-heard-of-a-dao-heres-why-its-going-to-become-hottest-new-type-of-corporation.html](https://www.inc.com/darren-heitner/never-heard-of-a-dao-heres-why-its-going-to-become-hottest-new-type-of-corporation.html)

### Additional information
Tag: DAOs

#### Deadline
By the end of the month, in time for Aragon Monthly issue 05

- [x] I would like to have a bounty on this Issue that I will fund myself

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x70290bf08b2b1ed530fc756cee4ce0f3f41516dba1320031f8e5a1637f15cb31](https://etherscan.io/tx/0x70290bf08b2b1ed530fc756cee4ce0f3f41516dba1320031f8e5a1637f15cb31)

**Comment by Smokyish** [comment]
Closed in #143
