### ISSUE TITLE
PROPULSANDO ARAGON EN LAS REDES

### ISSUE THREAD

**Issue by Adarves666** [aragon/aragon-monthly#12]
Bueno, os contaré a continuación como por casualidad mi mujer se fijo en ARAGON, ya que es una comunidad autónoma vecina a la nuestra, y me dijo mira esta criptomoneda, y le dije pues te voy a enseñar como se hace un analisis fundamental, nos fuimos a google y leimos el proyecto y vimos que era un proyecto español, basado en la jurisdiccion digital, que estaba en el puesto 36 de capitalización en Coinmarketcup y que llevaba funcionando desde Mayo del año pasado, me fui a ver el gráfico para enseñarle como se analizaba tecnicamente y vi que tenía en el histórico una enorme cuña descendente con un final de doble suelo, por lo que al otro día se lo comente a un amigo y moderador de un grupo de criptomonedas, y me dijo, mira si ha subido dos mil satoshis desde ayer, y la compre, y acto seguido se la envié a HAEJIN un famoso analista de steemit y twitter, al que siguen miles de personas en el mundo y en Corea su país natal, y este fue su analisis 
https://steemit.com/bitcoin/@haejin/aragon-ant-has-a-massive-cup-and-handle-potential-target-1-454-satoshi-then-0-0276-btc, al día siguiente mi amigo me dejo en el privado un enorme, NO TE LO VAS A CREER BUENOS DIAS. La verdad es que casi me caigo de la silla cuando vi que Haejin había analizado la cripto que le mandé por twitter, desde entonces mi amigo no deja de decirme que mi mujer es la DAMA DE ARAGON.

**Comment by Smokyish** [comment]
Thank you for the story, but i) English only please and ii) this is a place for content requests to Aragon Monthly.

Feel free to join https://aragon.chat/channel/spanish for Spanish discussion about Aragon.
