### ISSUE TITLE
Issue 01: News - Add Introducing aragonOS 3.0 alpha, the new operating system for protocols and DApps to News

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-monthly#14]
# Request for content

### Request type:
_News_

### Description of the requested content
Add [Introducing aragonOS 3.0 alpha, the new operating system for protocols and DApps](https://blog.aragon.one/introducing-aragonos-3-0-alpha-the-new-operating-system-for-protocols-and-dapps-348f7ac92cff) to News.

### Additional information
**Label:** Aragon

#### Deadline
By the end of the month, in time for Aragon Monthly issue 01

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xf1e706c57afb13fa4e07faa0538d76d68563f202ae6b739ef4ae3568efab095a](https://etherscan.io/tx/0xf1e706c57afb13fa4e07faa0538d76d68563f202ae6b739ef4ae3568efab095a)

**Comment by yermoo** [comment]
I share on my social networks

https://www.linkedin.com/feed/update/urn:li:activity:6363408011012112384
https://twitter.com/yermoo_network/status/958309296713891840
https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fyermooshare%2Fposts%2F1563716277016080

369 Thanks
