### ISSUE TITLE
Issue 01: News - Add Launch of Aragon Nest to News

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-monthly#15]
# Request for content

### Request type:
_News_

### Description of the requested content
Add [Launch of Aragon Nest](https://blog.aragon.one/launch-of-aragon-nest-8d42d1a37595) to News.

### Additional information
**Label:** Aragon

#### Deadline
By the end of the month, in time for Aragon Monthly issue 01

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x78db8c108c863007d38d4aab645ea4d7270b8d1433fc5b6a1b8f03017406f5d9](https://etherscan.io/tx/0x78db8c108c863007d38d4aab645ea4d7270b8d1433fc5b6a1b8f03017406f5d9)

**Comment by yermoo** [comment]
Add Launch of Aragon Nest to News:
I share on my social networks

https://www.linkedin.com/feed/update/urn:li:activity:6364055006374563840

https://twitter.com/yermoo_network/status/958293814732644352

https://www.facebook.com/plugins/post.phphref=https%3A%2F%2Fwww.facebook.com%2Fyermooshare%2Fposts%2F1563679967019711

Thank you

**Comment by djbohr13** [comment]
I have a pull request in for Issue 01: Introduction to district0x #23 that also addresses this
