### ISSUE TITLE
Issue 06 - Article: Freeform article about governance

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-monthly#153]
# Request for content

### Request type:
Article

#### Content type:
Opinion piece

### Description of the requested content
Thoughtful, freeform article on the subject `governance`. You have the freedom to write an editorial piece of your choosing.

**Article must be original content created for this purpose and not published anywhere before this**.

> An opinion piece is an article that mainly reflects the author's opinion about the subject. Opinion pieces in the newspaper are often written by a subject-matter expert, a person with a unique perspective on an issue.

### Additional information
Minimum 1500 words, maximum 2500 words

#### Deadline
By the end of June, in time for Aragon Monthly issue 06
___
## Notes

We will allow for a **maximum of 3 revisions** to the Pull Request based on feedback given by the Monthly staff, if the PR still doesn't meet the quality and standard, we will close the PR.

This issue **should be finished and merged as soon as possible**, this is first-come, first-served; the first proper Pull Request will be merged and will be awarded the associated bounty.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x7ba1aac8fe6eb166525717f20fe76e33a2b31e8b517b3be57928504c36e7e6de](https://etherscan.io/tx/0x7ba1aac8fe6eb166525717f20fe76e33a2b31e8b517b3be57928504c36e7e6de)

**Comment by marikio** [comment]
I'm going to start working on this.

**Comment by ThijsMaasLaw** [comment]
Could you check my submission and tell me if its alright?

**Comment by Smokyish** [comment]
@marikio Hi, if you still have something you are/were working on, please submit a new issue here in the repository for the article and we will consider it for another bounty!

**Comment by marikio** [comment]
Hey @Smokyish, believe I did everything correctly here: https://github.com/aragon/aragon-monthly/pull/174

Please let me know if I made a mistake somewhere. New to Github. Thanks!
