### ISSUE TITLE
Token Curated Registries: The Curation Protocol That Separates the Wheat from the Chaff

### ISSUE THREAD

**Issue by shyblugs** [aragon/aragon-monthly#16]

**Comment by Smokyish** [comment]
@shyblugs Thanks for the submission!

This doesn't really follow the [Guide for submitting a new Issue](https://monthly.aragon.one/guides/guide_for_submitting_a_new_issue/), but associated PR one does.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x3b06f5be5d479c3ee5e2750a2ac6992f59f2096b5688019e887a3956ab35270e](https://etherscan.io/tx/0x3b06f5be5d479c3ee5e2750a2ac6992f59f2096b5688019e887a3956ab35270e)

**Comment by Bradymck** [comment]
I'll do some editing though I could use another proofread before it's merged.
