### ISSUE TITLE
PROPULSING ARAGON IN THE NETWORKS

### ISSUE THREAD

**Issue by Adarves666** [aragon/aragon-monthly#17]
Well, I'll tell you later how by chance my wife noticed ARAGON, since it's an autonomous community next to ours, and she told me to look at this cryptocurrency, and I told her I'll show you how to do a fundamental analysis, We went to google and read the project and saw that it was a Spanish project, based on the digital jurisdiction, which was in the position 36 of capitalization in Coinmarketcup and had been running since May of last year, I went to see the graph to show how it was analyzed technically and I saw that it had a huge falling wedge in the historic one with a double floor finish, so the next day I told a friend and moderator of a group of cryptocurrencies, and he said, look if he has uploaded two thousand satoshis since yesterday, and I bought it, and then sent it to HAEJIN a famous analyst of steemit and twitter, followed by thousands of people in the world and in Korea, his native country, and this was his analysis
https://steemit.com/bitcoin/@haejin/aragon-ant-has-a-massive-cup-and-handle-potential-target-1-454-satoshi-then-0-0276-btc, the next day My friend left me in the private a huge, YOU WILL NOT GO TO BELIEVE GOOD DAYS. The truth is that I almost fell from the chair when I saw that Haejin had analyzed the crypto that I sent him on twitter, since then my friend does not stop telling me that my wife is the LADY OF ARAGON.

**Comment by Smokyish** [comment]
This is a place for content requests to Aragon Monthly, please stop the spam.
