### ISSUE TITLE
Freeform article on governance (Additional)

### ISSUE THREAD

**Issue by marikio** [aragon/aragon-monthly#173]
# Request for content

_Be sure to check out the [Guide for submitting a new Issue](https://monthly.aragon.one/guides/guide_for_submitting_a_new_issue/) for submitting a new request_

### Request type:
_Article_ 

#### Content type:
_Opinion Piece_

### Description of the requested content
Thoughtful, freeform article on the subject governance. You have the freedom to write an editorial piece of your choosing.

### Additional information
Minimum 1500 words, maximum 2500 words

#### Deadline
By the end of the month, in time for Aragon Monthly issue #06

**Comment by Smokyish** [comment]
Hi @marikio and thanks for the submission! This won't make it in time for Issue 06 so we will start reviewing it and possibly giving you feedback and then it can be considered for Issue 07!

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x15b29c69c3560dc646c905c5e18d666ae9d3a6c44b4cbbf0dfc3523d93f0ce7e](https://etherscan.io/tx/0x15b29c69c3560dc646c905c5e18d666ae9d3a6c44b4cbbf0dfc3523d93f0ce7e)
