### ISSUE TITLE
Issue 07 - Classified of open positions at P2P Models

### ISSUE THREAD

**Issue by sembrestels** [aragon/aragon-monthly#180]
# Request for content

_Be sure to check out the [Guide for submitting a new Issue](https://monthly.aragon.one/guides/guide_for_submitting_a_new_issue/) for submitting a new request_

### Request type:
_Classified_

#### Content type:
N/A

### Description of the requested content
Hello, we are hiring at P2P Models and would like to publish these two classifieds in the next aragon-monthly. Thanks!

### Additional information

[<h2>**Senior software dev/architect at P2P Models**</h2>](https://p2pmodels.eu/jobs-senior-dev/) |
:-----------|
[P2P Models](https://p2pmodels.eu/) is a 5-year (2018-2022) EU-funded (1.5M€) project around blockchain and the commons, which will be based at the Universidad Complutense de Madrid (Spain). More in this [thread](https://twitter.com/p2pmod/status/1017802485422067713). **We are looking for a Senior Software Developer/Architect** to lead the development of a blockchain-based framework to build collaborative Decentralized Autonomous Organizations. This role involves to establish the architectural foundations and develop a software framework to build modular components of DAOs, with a focus on supporting collaboration and communities. |
[Learn More](https://p2pmodels.eu/jobs-senior-dev/)

[<h2>**Project Manager / Communication Manager at P2P Models**</h2>](https://p2pmodels.eu/jobs-project-manager/) |
:-----------|
[P2P Models](https://p2pmodels.eu/). P2P Models aim is to build decentralized, democratic & sustainable Collaborative Economy organizations, aided by blockchain technologies. More in this [thread](https://twitter.com/p2pmod/status/1017802485422067713). **We are looking for a (Research) Project Manager / Communication Manager** for an interdisciplinary research project around blockchain and P2P communities.  This role involves the day-to-day and ongoing operations for the project and the facilitation of  the project social impact. |
[Learn More](https://p2pmodels.eu/jobs-project-manager/)

#### Deadline
By the end of the month, in time for Aragon Monthly issue #7

- [ ] I would like to have a bounty on this Issue that I will fund myself

**Comment by Smokyish** [comment]
https://github.com/aragon/aragon-monthly/pull/185
