### ISSUE TITLE
Issue 07 - Add Deploying and distributing Aragon Core to News

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-monthly#181]
# Request for content

_Be sure to check out the [Guide for submitting a new Issue](https://monthly.aragon.one/guides/guide_for_submitting_a_new_issue/) for submitting a new request_

### Request type:
_News_

### Description of the requested content
https://blog.aragon.one/deploying-and-distributing-aragon-core-11e70cbc9b50

#### Deadline
By the end of the month, in time for Aragon Monthly issue 07

**Comment by Smokyish** [comment]
https://github.com/aragon/aragon-monthly/pull/185
