### ISSUE TITLE
Issue 08 - Add Can blockchain reinvent justice systems? to News

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-monthly#196]
# Request for content

### Request type:
_News_

### Description of the requested content
https://blogs.thomsonreuters.com/answerson/cryptoeconomics-blockchain-reinvent-justice-sytems-kleros/

#### Deadline
By the end of the month, in time for Aragon Monthly issue 08

**Comment by Smokyish** [comment]
Closed in #202
