### ISSUE TITLE
Issue 10 - Add Announcing AraCon to News

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-monthly#216]
### Request type:
_News_

### Description of the requested content
https://blog.aragon.org/announcing-aracon-the-aragon-conference/

#### Deadline
By the end of the month, in time for Aragon Monthly issue 10

**Comment by krrisis** [comment]
this is now in 9 (sorry for the ridiculous delay 🙈 ) guess it's best to repeat this one for issue 10 as well?
