### ISSUE TITLE
Issue 01: Introduction to district0x

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-monthly#23]
### Request type:

_News_

### Description of the requested content

Add [this great summary](https://cryptoslate.com/introduction-district0x-network-decentralized-communities/) about the district0x network to the News section

### Additional information

Label: district0x

#### Deadline
By the end of the month, in time for Aragon Monthly issue 01

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xb80628ee204f026a788174936a8b059b4a7dd66b27db9025f9dee8704c6eb01b](https://etherscan.io/tx/0xb80628ee204f026a788174936a8b059b4a7dd66b27db9025f9dee8704c6eb01b)

**Comment by yermoo** [comment]
I share on my social networks

https://twitter.com/yermoo_network/status/958299195047383040
https://www.linkedin.com/feed/update/urn:li:activity:6364063918070988800
https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fyermooshare%2Fposts%2F1563695550351486

369 Thanks
