### ISSUE TITLE
Issue 02 - Add Bringing DAOs back — Aragon Monthly to News

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-monthly#30]
# Request for content

### Request type:
_News_

### Description of the requested content
Add Bringing DAOs back — Aragon Monthly, https://blog.aragon.one/bringing-daos-back-aragon-monthly-92756cb65639 to News.

### Additional information
Tag: Aragon

#### Deadline
By the end of the month, in time for Aragon Monthly issue 02

**Comment by djbohr13** [comment]
Can i grab all the news updates for issue 02? Will open a PR when i get home

**Comment by Smokyish** [comment]
@djbohr13 Sure, they will be filled as first come first served and we always appreciate community contributions!

But do note that we might not always fund every issue with a bounty, the idea would be to have the community be active in itself without needing to fund everything.

**Comment by djbohr13** [comment]
Yup, im totally for it. Not every one needs to be a paid bounty. Just happy
to help a project that i love 😊
