### ISSUE TITLE
Issue 12 - add Resources for decentralized organizing to News

### ISSUE THREAD

**Issue by krrisis** [aragon/aragon-monthly#306]
### Request type:
 _News_

### Description of the requested content

https://hackmd.io/s/Skh_dXNbE

**Comment by john-light** [comment]
Duplicate of https://github.com/aragon/aragon-monthly/issues/301

**Comment by krrisis** [comment]
haha, so strange! I really looked for this and when typing it, it didn't show up 🙈 If we continue with the monthly we'll need to implement that bot one day :)
