### ISSUE TITLE
Issue 02 - Add Decentralized Governance Matters to News

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-monthly#32]
# Request for content

### Request type:
_News_

### Description of the requested content
Add Decentralized Governance Matters, https://medium.com/daostack/decentralized-governance-first-principles-1fc6eaa492ed to News.

### Additional information
Tag: DAOs

#### Deadline
By the end of the month, in time for Aragon Monthly issue 02

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xad308fa20a3f4f388d3f4fbedd27594f095f3f45bfa432461a0bb507907fdd00](https://etherscan.io/tx/0xad308fa20a3f4f388d3f4fbedd27594f095f3f45bfa432461a0bb507907fdd00)
