### ISSUE TITLE
Issue 02 - Add Building a decentralised business on Ethereum to News

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-monthly#33]
# Request for content

### Request type:
_News_

### Description of the requested content
Add Building a decentralised business on Ethereum, https://mybroadband.co.za/news/cryptocurrency/246104-building-a-decentralised-business-on-ethereum.html to News.

### Additional information
Tag: Ecosystem

#### Deadline
By the end of the month, in time for Aragon Monthly issue 02

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x713344fafbdfb7c7e504135205936d1df9c115dcc3bf3587e6c071d5852c71c5](https://etherscan.io/tx/0x713344fafbdfb7c7e504135205936d1df9c115dcc3bf3587e6c071d5852c71c5)
