### ISSUE TITLE
Issue 02 - Add 2018 — The DAOs return to News

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-monthly#34]
# Request for content

### Request type:
_News_

### Description of the requested content
Add 2018 — The DAOs return, https://blog.goodaudience.com/2018-the-dao-returns-5868a473afb0 to News.

### Additional information
Tag: DAOs

#### Deadline
By the end of the month, in time for Aragon Monthly issue 02

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xc2bd3742735c34eeecad14b5033828155ba7d8751004daf4e1847e242542284b](https://etherscan.io/tx/0xc2bd3742735c34eeecad14b5033828155ba7d8751004daf4e1847e242542284b)
