### ISSUE TITLE
Issue 02 - Add Aragon Team Update: January 2018 to News

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-monthly#35]
# Request for content

### Request type:
_News_

### Description of the requested content
Add Aragon Team Update: January 2018, https://blog.aragon.one/aragon-team-update-january-2018-aacd32b709ed to News.

### Additional information
Tag: Aragon

#### Deadline
By the end of the month, in time for Aragon Monthly issue 02

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x237caa5072fb50fafd5914cfeadb5bc30a0762813982771e1e71f5070af7443f](https://etherscan.io/tx/0x237caa5072fb50fafd5914cfeadb5bc30a0762813982771e1e71f5070af7443f)
