### ISSUE TITLE
Issue 02 - Add Announcing Aragon Labs to News

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-monthly#36]
# Request for content

### Request type:
_News_

### Description of the requested content
Add Announcing Aragon Labs, https://blog.aragon.one/announcing-aragon-labs-a679693429ae to News.

### Additional information
Tag: Aragon

#### Deadline
By the end of the month, in time for Aragon Monthly issue 02

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x942f1a75c9e934ff73311e7b123df8c952a65ec11457e4842ec8d3737edce4be](https://etherscan.io/tx/0x942f1a75c9e934ff73311e7b123df8c952a65ec11457e4842ec8d3737edce4be)
