### ISSUE TITLE
Issue 02 - Add Decentralizing Aragon’s development to News

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-monthly#37]
# Request for content

### Request type:
_News_

### Description of the requested content
Add Decentralizing Aragon’s development, https://blog.aragon.one/decentralizing-aragons-development-5062fd6d135d to News.

### Additional information
Tag: Aragon

#### Deadline
By the end of the month, in time for Aragon Monthly issue 02

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x992c1b0e426456fc8df9db31dd686ba90eebe5ede1c0ede16d4895f1c43865e4](https://etherscan.io/tx/0x992c1b0e426456fc8df9db31dd686ba90eebe5ede1c0ede16d4895f1c43865e4)
