### ISSUE TITLE
Issue 02 - Add What Is Aragon? to News

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-monthly#38]
# Request for content

### Request type:
_News_

### Description of the requested content
Add What Is Aragon?, https://themerkle.com/what-is-aragon/ to News.

### Additional information
Tag: Aragon

#### Deadline
By the end of the month, in time for Aragon Monthly issue 02

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x86f19bce587d61e77060d3deedc2a76aebf2b00249e05482369249261b1676b3](https://etherscan.io/tx/0x86f19bce587d61e77060d3deedc2a76aebf2b00249e05482369249261b1676b3)
