### ISSUE TITLE
Issue 02 - Add Space Decentral: Using Blockchain Tech to Democratize Space to News

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-monthly#39]
# Request for content

### Request type:
_News_

### Description of the requested content
Add Space Decentral: Using Blockchain Tech to Democratize Space, https://bitcoinmagazine.com/articles/space-decentral-using-blockchain-tech-democratize-space/ to News.

### Additional information
Tag: Ecosystem

#### Deadline
By the end of the month, in time for Aragon Monthly issue 02

**Comment by djbohr13** [comment]
@Smokyish I can take care of all the news updates if you want to assign them to me. I'll get them started this weekend.

**Comment by Smokyish** [comment]
@djbohr13 That sounds great, but I can only assign people who have been added to the repo with push access.

You're contributions are most welcome, feel free to do as many as you want and can, it is always most welcome.

**Comment by djbohr13** [comment]
Gotcha. Well, regardless, I'll get started/finished the majority of this on
the weekend.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xd23a768cf37d9f8c7e5671bd57dcdc0c04eb1134b90b90ac4d95927e02b58650](https://etherscan.io/tx/0xd23a768cf37d9f8c7e5671bd57dcdc0c04eb1134b90b90ac4d95927e02b58650)

**Comment by djbohr13** [comment]
@Smokyish alright. ill be resubmitting shortly. also. when will the bounties from the previous issue be paid out? i'm still expecting 6 ANT from that

**Comment by Smokyish** [comment]
@djbohr13 Sorry that it has taken so long, we still need our SOB maintainer to confirm the payouts and he's been very busy. Once that gets confirmed I will be able to send the 4 ANT to you that will be missing as we only learned after closing the PR that we can only have one Issue closed per PR for the bounties to work and I will need to get your address in order to send out the missing ANT which i can get once the first one is confirmed through SOB.
