### ISSUE TITLE
Issue 02 - Add The Decentralized Future Series to News

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-monthly#40]
# Request for content

### Request type:
_News_

### Description of the requested content
Add The Decentralized Future Series, http://blog.ycombinator.com/the-decentralized-future-series/ to News.

### Additional information
Tag: Ecosystem

#### Deadline
By the end of the month, in time for Aragon Monthly issue 02

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x9167793c6ce442aec51b86493f55d66775b95a7eb94d531d07c1894a7441f906](https://etherscan.io/tx/0x9167793c6ce442aec51b86493f55d66775b95a7eb94d531d07c1894a7441f906)
