### ISSUE TITLE
Issue 06 - Article: Importance of governance

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-monthly#41]
# Request for content

### Request type:
Article

#### Content type:
Opinion Piece

### Description of the requested content
Thoughtful article on the subject `Importance of governance`.
The article should really help the reader grasp how and *why* governance is important in the decentralized context. Why should organizations care about governance?

### Additional information
Minimum 500 words, maximum 1500 words

#### Deadline
By the end of May, in time for Aragon Monthly issue 06

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xff2b30f999cf52b5100bd0d90c5ad50c6ea6b7faeddcdfb6e30b2e79dcbe75a8](https://etherscan.io/tx/0xff2b30f999cf52b5100bd0d90c5ad50c6ea6b7faeddcdfb6e30b2e79dcbe75a8)
