### ISSUE TITLE
Issue 02 - Add Ocean Protocol Technical Whitepaper to News

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-monthly#43]
# Request for content

### Request type:
_News_

### Description of the requested content
Add Ocean Protocol Technical Whitepaper, https://blog.oceanprotocol.com/ocean-protocol-technical-whitepaper-c012daf12f2e to News.

### Additional information
Tag: Governance

#### Deadline
By the end of the month, in time for Aragon Monthly issue 02

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x20634c7924bd4535f70fc6290b52d9f1a30e3891dfa435ef3a3075812c1b83f7](https://etherscan.io/tx/0x20634c7924bd4535f70fc6290b52d9f1a30e3891dfa435ef3a3075812c1b83f7)
