### ISSUE TITLE
Issue 02 - Add Saving The Planet: Making It Profitable To Protect The Commons. to News

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-monthly#44]
# Request for content

### Request type:
_News_

### Description of the requested content
Add Saving The Planet: Making It Profitable To Protect The Commons., https://medium.com/@simondlr/saving-the-planet-making-it-profitable-to-protect-the-commons-50393906fe22 to News.

### Additional information
Tag: Governance

#### Deadline
By the end of the month, in time for Aragon Monthly issue 02

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xf11137fb315f86c5e9dba08e490ddb91b3231760d7cb155525d212c3aafd87c2](https://etherscan.io/tx/0xf11137fb315f86c5e9dba08e490ddb91b3231760d7cb155525d212c3aafd87c2)
