### ISSUE TITLE
Issue 02 - Add Democratically Mutable DAO: A proposition for a fairer blockchain governance to News

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-monthly#45]
# Request for content

### Request type:
_News_

### Description of the requested content
Add Democratically Mutable DAO: A proposition for a fairer blockchain governance, https://mislavjavor.github.io/2018-02-21/Democratically-Mutable-DAO/ to News.

### Additional information
Tag: DAOs

#### Deadline
By the end of the month, in time for Aragon Monthly issue 02

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xd047d5b05fd40ddbfac87c8abfbd5ea320addd03804f2b14562a4216b3d76551](https://etherscan.io/tx/0xd047d5b05fd40ddbfac87c8abfbd5ea320addd03804f2b14562a4216b3d76551)
