### ISSUE TITLE
Issue 02 - Add Front-running, Griefing and the Perils of Virtual Settlement (Part 2) to News

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-monthly#47]
# Request for content

### Request type:
_News_

### Description of the requested content
Add Front-running, Griefing and the Perils of Virtual Settlement (Part 2), https://blog.0xproject.com/front-running-griefing-and-the-perils-of-virtual-settlement-part-2-921b00109e21 to News.

### Additional information
Tag: Ecosystem

#### Deadline
By the end of the month, in time for Aragon Monthly issue 02

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xd03ff4299624f5862f2830ccbc3a1e0538cc707478a9142d8d9e3da15ff89184](https://etherscan.io/tx/0xd03ff4299624f5862f2830ccbc3a1e0538cc707478a9142d8d9e3da15ff89184)
