### ISSUE TITLE
Issue 02 - Add Conspiratus Podcast #1: Protocol Governance with Vlad Zamfir and Arthur Breitman to News

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-monthly#48]
# Request for content

### Request type:
_News_

### Description of the requested content
Add Conspiratus Podcast #1: Protocol Governance with Vlad Zamfir and Arthur Breitman, https://www.youtube.com/watch?v=IDY_inT-q0U to News.

### Additional information
Tag: Governance

#### Deadline
By the end of the month, in time for Aragon Monthly issue 02

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xd03ff4299624f5862f2830ccbc3a1e0538cc707478a9142d8d9e3da15ff89184](https://etherscan.io/tx/0xd03ff4299624f5862f2830ccbc3a1e0538cc707478a9142d8d9e3da15ff89184)
