### ISSUE TITLE
Issue 02 - Add An open invitation to participate in a Fellowship of Ethereum Magicians to News

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-monthly#49]
# Request for content

### Request type:
_News_

### Description of the requested content
Add An open invitation to participate in a Fellowship of Ethereum Magicians, https://medium.com/@jpitts/an-open-invitation-to-participate-in-a-fellowship-of-ethereum-magicians-982e6143db4f to News.

### Additional information
Tag: Governance

#### Deadline
By the end of the month, in time for Aragon Monthly issue 02

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xd1dfe9f0e6004a35a0d4b4fa36b36225d7c89b6bb998f5db801ec441909ea4d2](https://etherscan.io/tx/0xd1dfe9f0e6004a35a0d4b4fa36b36225d7c89b6bb998f5db801ec441909ea4d2)
