### ISSUE TITLE
test

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-monthly#5]
# Request for content

_Be sure to check out the [Guide for submitting a new Issue](https://monthly.aragon.one/guides/guide_for_submitting_a_new_issue/) for submitting a new request_

### Request type:
_Article_ / _Column_ / _News_

#### Content type:
_Opinion Piece_ / _Editorial_ / _Column_

### Description of the requested content
I would like to read an article about DAOS

### Additional information
Minimum 500 words, maximum 1500 words

#### Deadline
By the end of the month, in time for Aragon Monthly issue #X

- [x] I would like to have a bounty on this Issue that I will fund myself

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x40ee0f6912472439edb680f49e58dfa706c10772f3c785e10556b5505a7b2c49](https://etherscan.io/tx/0x40ee0f6912472439edb680f49e58dfa706c10772f3c785e10556b5505a7b2c49)
