### ISSUE TITLE
Issue 01 - Article: Add links to Thoughts On Governance and Network Effects

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-monthly#6]
# Request for additions

### Request category:
Article

#### Content type:
Fix / Addition

### Description of the request
The article [Thoughts On Governance and Network Effects](https://monthly.aragon.one/articles/opinion/thoughts_on_governance_network_effects/) was originally posted at https://blog.aragon.one/thoughts-on-governance-and-network-effects-f40fda3e3f98

It is missing all the links from the blog post, add those to the newspaper version.

#### Deadline
By the end of January, in time for Aragon Monthly issue 01

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x510f3e59d81452100d3541d9906d45e335358b6ab2dc507d8afedb0e00a2ab67](https://etherscan.io/tx/0x510f3e59d81452100d3541d9906d45e335358b6ab2dc507d8afedb0e00a2ab67)
