### ISSUE TITLE
Issue 01 - Article: Add links to The district0x network in a nutshell

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-monthly#7]
# Request for additions

### Request category:
Article

#### Content type:
Fix / Addition

### Description of the request
The article [The district0x network in a nutshell](https://monthly.aragon.one/articles/editorial/the_district0x_in_a_nutshell/) was originally posted at https://blog.district0x.io/the-district0x-network-in-a-nutshell-864a391e0b4

It is missing all the links from the blog post, add those to the newspaper version.

#### Deadline
By the end of January, in time for Aragon Monthly issue 01

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xc0e07d4b3f887788f594539c19c8fcfd630a7a64ff28906b0f3306833299b7ff](https://etherscan.io/tx/0xc0e07d4b3f887788f594539c19c8fcfd630a7a64ff28906b0f3306833299b7ff)

**Comment by Smokyish** [comment]
@roundminer The bounty bot did not pick this up from your previous Pull Request. Could you submit an empty PR with the description `Closes #7` so that we can reward you the bounty successfully.

**Comment by roundminer** [comment]
I have added an empty PR with just a file added to root folder. I hope this will be fine.

**Comment by roundminer** [comment]
And don't merge this empty PR :) This is based on previous master without my changes with fixed links. I didn't realise merge wasn't updated on my fork. 
If I need to create different PR with some specifics, let me know, i will fix it.

**Comment by Smokyish** [comment]
@roundminer Thanks, the empty one looked fine so merged it.

The first merged PR with the previous bounty doesn't seem to appear at https://openbounty.status.im/app#/activity for some reason right now after i tried to link it to this issue, will confirm that the payout gets sent.

**Comment by roundminer** [comment]
Are there any news regarding payout of issue #6?

**Comment by Smokyish** [comment]
@roundminer Will continue to look into this.
