### ISSUE TITLE
Issue 04 - add Malta Blockchain Regulation Proposal to News

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-monthly#86]
# Request for content

_Be sure to check out the [Guide for submitting a new Issue](https://monthly.aragon.one/guides/guide_for_submitting_a_new_issue/) for submitting a new request_

### Request type:
_News_

### Description of the requested content
https://chainstrategies.com/2018/03/11/malta-blockchain-regulation-proposal-legal-personality-for-daos-and-smart-contracts/

### Additional information

Tag: DAOs

#### Deadline
By the end of the month, in time for Aragon Monthly issue 03

- [x] I would like to have a bounty on this Issue that I will fund myself

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xc2d48f727b44d25a9c50c82907e11e43b80dc6867cda57fad9b3b3ccd40e1658](https://etherscan.io/tx/0xc2d48f727b44d25a9c50c82907e11e43b80dc6867cda57fad9b3b3ccd40e1658)

**Comment by bling5630** [comment]
dear John,
I solve this issue and try to submit a PR, but somehow can't implement it. Can you help me out what should I do? 
thank you in advance,
Tamas

**Comment by Smokyish** [comment]
Closed in #138
