### ISSUE TITLE
Issue 04 - add Collaborare — The Ugly DAOckling #1 to news

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-monthly#87]
# Request for content

_Be sure to check out the [Guide for submitting a new Issue](https://monthly.aragon.one/guides/guide_for_submitting_a_new_issue/) for submitting a new request_

### Request type:
_News_

### Description of the requested content
https://medium.com/@joselfgaray/collaborare-the-ugly-daockling-1-1233b596223d

### Additional information
Tag: DAOs

#### Deadline
By the end of the month, in time for Aragon Monthly issue 03

- [x] I would like to have a bounty on this Issue that I will fund myself

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xa14956c8d23c4cceef56178f34a012663385632f28762724b1c54577605f946b](https://etherscan.io/tx/0xa14956c8d23c4cceef56178f34a012663385632f28762724b1c54577605f946b)

**Comment by bling5630** [comment]
dear @john-light 

I would like to work on the further issues as well, and I wondering when could you evaluate my former pull requests

many thanks,

Tamas

**Comment by john-light** [comment]
@bling5630 thanks for sending the PRs! Just left feedback. Also, please sign the CLA when you get a chance. Just click the link on the CLA Assistant comment on your Pr.

**Comment by bling5630** [comment]
@john-light I finalized this issue as well, but unfortunately I made another pull request included this task as well. You find it under the "add Decentralization 2.0" issue, how can I fix this mistake?

**Comment by john-light** [comment]
@bling5630 you should be able to edit that commit to remove the content intended for this PR, then open a new PR and add the content back in with a comment that it closes this issue.

**Comment by Smokyish** [comment]
Closed in #138
