### ISSUE TITLE
Issue 04 - Add DAOs, Democracy and Governance to News

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-monthly#90]
# Request for content

_Be sure to check out the [Guide for submitting a new Issue](https://monthly.aragon.one/guides/guide_for_submitting_a_new_issue/) for submitting a new request_

### Request type:
_News_

### Description of the requested content
http://merkle.com/papers/DAOdemocracyDraft.pdf

### Additional information
Tag: DAOs

#### Deadline
By the end of the month, in time for Aragon Monthly issue 03

- [x] I would like to have a bounty on this Issue that I will fund myself

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x0ed72f19b7ecffdda152ea82e1bcfe0a67ab99e59f1d32f5bf022dfdebe937a7](https://etherscan.io/tx/0x0ed72f19b7ecffdda152ea82e1bcfe0a67ab99e59f1d32f5bf022dfdebe937a7)

**Comment by Smokyish** [comment]
Closed in #138
