### ISSUE TITLE
Issue 04 - Add "Pilot Experiment of the Space Decentral Collaboration Process" to News

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-monthly#94]
### Request type:
_News_

### Description of the requested content
https://blog.space.coop/pilot-experiment-of-the-space-decentral-collaboration-process-8d2b9bfe4aa2

### Additional information
Tag: DAOs

#### Deadline
By the end of the month, in time for Aragon Monthly issue 03

- [x] I would like to have a bounty on this Issue that I will fund myself

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xd2379500487c4f0bf73504ef54f94826dc35e33ae139941ec464cd79be41e39e](https://etherscan.io/tx/0xd2379500487c4f0bf73504ef54f94826dc35e33ae139941ec464cd79be41e39e)

**Comment by stefek99** [comment]
Thinking...

Don't get me wrong...

Maybe you'll explain how it works...

5 ANT to add 2 sentences to the news?

If someone is technical enough to use bounty system, that person is technical enough to add 2 sentences.

What am I missing here?

**Comment by john-light** [comment]
@stefek99 you're not missing anything. If you know how to add this item to the news then there's 5 ANT up for grabs if you can do it.

**Comment by stefek99** [comment]
@john-light I would argue that another condition should be met:
* AND ensure noone else hasn't already done it

My argument still stands:
> If someone is technical enough to use bounty system, that person is technical enough to add 2 sentences.

Now I'm assuming that `open-bounty-status-eth-ant` is somehow automated and easier to accomplish from the end-user perspective.

![image](https://user-images.githubusercontent.com/249703/39951702-478aa4ca-5584-11e8-9493-4afdb9430ae7.png)

**Comment by stefek99** [comment]
I'm not arguing, I'm not making any points.

See my very first message: https://github.com/aragon/aragon-monthly/issues/94#issuecomment-388468332

> Thinking...

> Don't get me wrong...

> Maybe you'll explain how it works...

> If someone is technical enough to use bounty system, that person is technical enough to add 2 sentences.

----


I'm learning my lessons.

I've asked question on the chat: https://aragon.chat/channel/general?msg=m69sMQruEZmJkAF6K

> Looking for more detailed explanation about Pay Protocol...

You are the person who asked: 

> Is it something you're interested in working on?

# Clearly our modes of communication are not compatible.

In my version of reality asking a question _(on Twitter, on StackOverflow, on aragon.chat)_ means that I mean to ask this question.

Never implied (implicitly, explicitly) that I'm...

My hovercraft is full of eels: https://www.youtube.com/watch?v=G6D1YI-41ao

**Comment by john-light** [comment]
@stefek99 

> I would **argue** that another condition should be met:
> 
>     AND ensure noone else hasn't already done it
> 
> My **argument** still stands:
> 
>     If someone is technical enough to use bounty system, that person is technical enough to add 2 sentences.

(emphasis mine)

That is what I am referring to by "arguing", since you yourself called your messages arguments. In any case, this is the wrong place to have this discussion. Please move your general questions to Aragon Chat and leave GitHub comments for questions or comments specifically about the issue at hand.
