### ISSUE TITLE
Issue 03 - add Prediction markets for content curation DAOs to News

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-monthly#95]
# Request for content

### Request type:
_News_

### Description of the requested content
Add Prediction markets for content curation DAOs, https://ethresear.ch/t/prediction-markets-for-content-curation-daos/1312 to News.

### Additional information
Tag: DAOs

**Comment by bling5630** [comment]
hi @Smokyish ,

I will do this issue,

Tamas
